// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://topkzcumjilaxbprufyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcGt6Y3VtamlsYXhicHJ1ZnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTE2NzMsImV4cCI6MjA3MDc4NzY3M30.i-hVEpjwL0umoW9NNPWl1L7xViOXVt_WtOGpUQCynjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});